### ISSUE TITLE
Could not download dataset !

### ISSUE THREAD

**Issue by feki-younes** [experimaestro/datamaestro_text#1]
I tried to download dataset using datamaestro

**`ds = prepare_dataset("com.sentiment140.english")`**

But I got this exception, is it a normal ? 

**`Exception: Could not find the dataset com.sentiment140.english`**

Did I make a mistake ? 
It is the first line of my script to gather data but it is not working. Did I miss something ?

Thanks,

**Comment by bpiwowar** [comment]
It should work if you installed datamaestro_text. Could you do a `pip freeze | grep maestro` so I can check the versions?

**Comment by bpiwowar** [comment]
Closing for now, please re-open if you have trouble
